info:
  app:
    name: API Gateway

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

zuul:
  routes:
    product-service:
      path: /api/v1/product/**
    user-service:
      path: /api/v1/user/**
    order-service:
      path: /api/v1/order/**
    host:
      connect-timeout-millis: 5000
      socket-timeout-millis: 10000

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
