info:
  app:
    name: Inventory service
    description: Inventory Microservice

server:
  port: 8282

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:h2:mem:inventorydb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2inventory
      enabled: true
      settings:
        trace: false
        web-allow-others: false
