info:
  app:
    name: Product service
    description: Product Microservice

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/


spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/catalog?useSSL=false

