server:
  port: 8761

spring:
  profiles: docker
  application:
    name: servis-registry

eureka:
  instance:
    prefer-ip-address: true
  server:
    enableSelfPreservation: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
