server:
  port: 8761

spring:
  application:
    name: servis-registry
  zipkin:
    base-url: http://192.168.1.4:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  instance:
    prefer-ip-address: true
  server:
    enableSelfPreservation: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
